### PR TITLE
fix(CI) Align GitHub workflows, remove old scripts

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

### Why

We need to do a second round of design on CI migration from Travis to GitHub Actions because:
1. we have to variants now with slightly different takes in https://github.com/accordproject/concerto/tree/master/.github/workflows and https://github.com/accordproject/cicero/tree/master/.github/workflows
2. We need to decide which node version we support
3. Better to maintain one well understood version to make our lives easier
4. Travis is being _very_ capricious and the matter feels more urgent than it was a year ago

### Changes

- Consolidate GitHub action workflows for build/testing/publication to npm

### Flags

- Still draft, one key question is when is `lerna` installed and how, but want this PR ready for discussion on Tech WG call

### CODE REVIEW

**Review by dselman — APPROVED** [review]
Looks great.

**Comment by irmerk** [comment]
Can we point these to https://github.com/accordproject/technical-steering-committee/issues/4?

**Review by irmerk — APPROVED** [review]

**Review by mttrbrts — APPROVED** [review]
> Has this script been used elsewhere? If not perhaps we should skip the NPM publish until we can run it live?

sigh. status:

we've had working scripts for a while in: `concerto` and `markdown-transform`

we've had recent working script added but different in `cicero`

this is my attempt at unifying those. my plan was:
1. align
2. merge and test concerto
3. update the other PR accordingly
4. merge and test cicero
5. update markdown transform
6. do the rest

**Comment by jeromesimeon** [comment]
PS> concerto 1.0 was published with the script currently in master

**Comment by jeromesimeon** [comment]
open questions:
1. `npm ci` (what Cicero currently use) or `npm -g install lerna` (what Concerto currently use)
2. do we run those on every PR to master every branch? do we publish on every branch? Current status in most of AP: run test on every PR on every branch, publish only on push but on every branch (which can be useful for long-running branches like `release-1.0`

**Comment by jeromesimeon** [comment]
> open questions:
> 
> 1. `npm ci` (what Cicero currently use) or `npm -g install lerna` (what Concerto currently use)

Turns out `npx lerna bootstrap`, as hinted in @dselman 's approach for Cicero works great! I like that a lot so I'll adjust the PR accordingly.

> 2. do we run those on every PR to master every branch? do we publish on every branch? Current status in most of AP: run test on every PR on every branch, publish only on push but on every branch (which can be useful for long-running branches like `release-1.0`

**Pull request merged**
