### PR TITLE
add TemplateLibrary http authentication

### PR DESCRIPTION
**Pull request by triebben**
# Issue #164 
Add http auth parameter to TemplateLibrary.
Extend test of TemplateLibrary.

### Changes
- HTTP Auth for TemplateLibrary

### Flags
- no flags

### CODE REVIEW

**Comment by irmerk** [comment]
Thanks for the PR! You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/cicero/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by jeromesimeon** [comment]
> Specifically, is there a scenario where I might want different credentials for templates in the same library, or is this a reasonable restriction, at least to begin with?
> 
> @dselman? @jeromesimeon ?
> 

To me having the credentials be on a per-library basis makes sense as a start. If the same user needs different credentials for distinct templates they could group in different libraries.

**Comment by dselman** [comment]
> > Specifically, is there a scenario where I might want different credentials for templates in the same library, or is this a reasonable restriction, at least to begin with?
> > @dselman? @jeromesimeon ?
> 
> To me having the credentials be on a per-library basis makes sense as a start (or maybe even in the long run). If the same user needs different credentials for distinct templates they could group in different libraries.

I agree.

**Comment by mttrbrts** [comment]
@triebben are you able to address the comments above, please?

1. `getTemplate` operations should also be authenticated
2. New code should have unit tests
3. Remove commented out code

**Comment by irmerk** [comment]
@triebben closing this as stale, feel free to open back up if you come back to it.

**Pull request closed without merging**
