### PR TITLE
feat(archive): add signing support (#262)

### PR DESCRIPTION
**Pull request by roysjosh**
Signed-off-by: Josh Roys <joshua.roys@kudelskisecurity.com>

# Issue #262 
Add signing support to template archives

### Changes
- Sign archives using PKCS#7
  - The signing cert and key are contained in a P12/PFX archive
  - The cert must have the codeSigning EKU bit set
  - All archive files are hashed using SHA256 and then a manifest containing those hashes is signed
- Verify signed archives
  - CA list is hard-coded to typical Linux paths of CA bundles
- Signing and verification is versioned allowing for future changes

### Flags
- **Do not merge** until node-forge PR is merged!
- Additionally, node-forge will likely need one further enhancement not in the current node-forge PR: support for extKeyUsage

### CODE REVIEW

**Comment by jeromesimeon** [comment]
For reviewers, pending forge issue is at https://github.com/digitalbazaar/forge/pull/706

**Comment by dselman** [comment]
@roysjosh I'd love to get this merged. What is the current status?

**Comment by roysjosh** [comment]
Activity in digitalbazaar/forge has stalled out a little.  I've pinged them again.  You could consider forking forge.

**Comment by dselman** [comment]
Any progress? Would love to get this merged...

**Comment by dselman** [comment]
I've pinged digitalbazaar/forge#706

**Comment by jeromesimeon** [comment]
Subsumed by #683

**Pull request closed without merging**
