### PR TITLE
feat(readme): add ecosystem table

### PR DESCRIPTION
**Pull request by daniloff200**
# Related to https://github.com/accordproject/techdocs/issues/80

### CODE REVIEW

**Comment by irmerk** [comment]
I think this should go in the AP section, similar to where it sits in https://github.com/accordproject/techdocs

**Comment by daniloff200** [comment]
Hm. Yeah, okay, I've just put it on the place, where's the previous map of repo was @irmerk

**Comment by irmerk** [comment]
Oh yes I see now. I think the ecosystem should be synced around the AP section. I think the repository structure part should remain the same.

**Comment by daniloff200** [comment]
oh, okay, gonna revert this back then

**Pull request merged**
