### PR TITLE
Add Cicero's direct weblink as Hyperlink to cicero logo

### PR DESCRIPTION
**Pull request by midhunbiju**
Signed-off-by: midhunbiju <midhunbijutvm@gmail.com>
Author: midhunbiju <midhunbijutvm@gmail.com>

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
modified:   README.md

Signed-off-by: midhunbiju <midhunbijutvm@gmail.com>

### CODE REVIEW

**Comment by midhunbiju** [comment]
@irmerk Did I signed off DCO correctly this time?

**Comment by midhunbiju** [comment]
@irmerk  why continuous-integration/travis-ci/pr  Test is showing failed ?

**Comment by irmerk** [comment]
@jeromesimeon I think the travis build just needs to retry but I don't have access.

**Comment by midhunbiju** [comment]
@irmerk  Hey, Now All the 3 Checks have Passed.

**Pull request merged**
