### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by pranjalv9**
# Issue #<NUMBER HERE>
<OVERALL SUMMARY OF PULL REQUEST>

added copyright details

### Changes
- <INSERT DESCRIPTION OF CHANGES>
  - <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by irmerk** [comment]
@peterhunn and @dselman is this an edit to the `LICENSE` that we need?

**Comment by jeromesimeon** [comment]
We also want to make sure that this is not going to break the LICENSE detection in GitHub.

Screenshot 2019-10-05 at 10 13 46 AM

**Comment by jeromesimeon** [comment]
> We also want to make sure that this is not going to break the LICENSE detection in GitHub.
> 
> Screenshot 2019-10-05 at 10 13 46 AM

You can check that this will work using https://github.com/licensee/licensee which is what GitHub uses.

**Comment by jeromesimeon** [comment]
I would love to have a rational for _why_ the change. Many big projects use the same approach we do e.g., https://github.com/tensorflow/tensorflow

**Comment by mttrbrts** [comment]
@pranjalv9 your original changes have been over-written by your force-push.

I suggest closing this PR and instead working on items from https://www.accordproject.org/events/hacktoberfest-2019/

**Pull request closed without merging**
