### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by midhunbiju**
Hyperlinked Cicero link to the above logo

# Issue #<NUMBER HERE>
added Cicero link as hyper link to the logo in Readme.md file

### Changes
- Added Link

This is my commit message

Signed-off-by: Midhun Biju <midhunbijutvm@gmail.com>

### CODE REVIEW

**Comment by midhunbiju** [comment]
This is my commit message

Signed-off-by: Midhun Biju <midhunbijutvm@gmail.com>

**Comment by midhunbiju** [comment]
@irmerk Sir, In other pages, the logos are hyperlinked to their respective web links. That helps people to go to the website directly by clicking on the logo. That's why I added the web link of Cicero as a hyperlink on the logo.

**Comment by irmerk** [comment]
This is more useful than linking it to the folder where it is kept. You'll still need to update the DCO signoff.

**Comment by midhunbiju** [comment]
@irmerk 
Hai I'm facing an issue doing DCO Sign off.

__________________________________________________________
Midhun Biju@DESKTOP-L0MEQJ8 MINGW32 ~
$ cd cicero

Midhun Biju@DESKTOP-L0MEQJ8 MINGW32 ~/cicero (master)
$ git commit --amend --signoff
[master 6512fa0] Update README.md #437
 Author: Arshad Kazmi <arshadkazmi42@gmail.com>
 Date: Wed Oct 16 22:10:39 2019 +0530
 1 file changed, 1 insertion(+), 1 deletion(-)

Midhun Biju@DESKTOP-L0MEQJ8 MINGW32 ~/cicero (master)
$ git push --force-with-lease origin patch-1
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/accordproject/cicero.git'
__________________________________________________________________________________________

These are the steps I done for doing DCO Sign off.Am I did correctly or have any mistake ?
I'm getting the above error.Please help me to correclty do DCO Signoff

**Comment by irmerk** [comment]
@midhunbiju it's possible that you should be doing `-f` instead of `--force-with-lease`

**Pull request closed without merging**
