### PR TITLE
fix:core upgrade winston

### PR DESCRIPTION
**Pull request by alexCatena**
winston upgrade to fix compatibility issues with create-react-app

### CODE REVIEW

**Comment by jeromesimeon** [comment]
Thanks for the contribution, @alexCatena. We enforce DCO rules on the project, you can see the guidelines here: https://github.com/organizations/accordproject/settings/installations/130423

To add a DCO signature to your PR, this usually does the trick:
```
git commit --amend -s
git push --force
```

**Comment by alexCatena** [comment]
Is there a way that I can use this pull request in my project in the while i wait for a new version to be released

**Comment by jeromesimeon** [comment]
Once merged, the build process should create an 'unstable' version on npm, similar to:
https://www.npmjs.com/package/@accordproject/cicero-core/v/0.10.2-20190129142217

**Comment by alexCatena** [comment]
Thank you very much

**Pull request merged**
