### PR TITLE
Added CICERO_DATA environment variable to Cicero Server API

### PR DESCRIPTION
**Pull request by martinhalford**
# Issue #514  
Added CICERO_DATA environment variable to Cicero Server API in order to allow data files to be located separately to the template archives.

### Changes
- Added reference to CICERO_DATA environment variable when creating `data` constant.
  - e.g. `${process.env.CICERO_DATA}/${req.params.template}/${req.params.data}`
- Added error handling to check that CICERO_DATA environment set prior to server start.
- Added test to check that error handling for CICERO_DATA environment is functioning.

### CODE REVIEW

**Comment by martinhalford** [comment]
Closing pull request.

**Comment by martinhalford** [comment]
Reopening for review.

**Comment by martinhalford** [comment]
> Looks good! I would just suggest to make CICERO_DATA optional and fall back to CICERO_DIR. This will make it backward compatible as well.

Okay... I can do that.  Good idea.

**Comment by martinhalford** [comment]
> I'm also realising this PR includes commits that seem to have been already merged? If so please rebase with master to clean up this PR. This will avoid conflicts/duplication.

Okay... I'll try a rebase and that should fix that.

**Comment by jeromesimeon** [comment]
Rebased / squashed and moved to #537

**Pull request closed without merging**
