### PR TITLE
(fix) Lets Cicero Version-Timestamp load templates compatible with Ve…

### PR DESCRIPTION
**Pull request by jeromesimeon**
…rsion

Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

### CODE REVIEW

**Comment by jeromesimeon** [comment]
A fix for #275

**Comment by mttrbrts** [comment]
Or otherwise, relax the target version int he template? e.g. https://github.com/accordproject/cicero-template-library/blob/bb82e02bc805bbede6cdcaa93eddb32d38321704/src/acceptance-of-delivery/package.json#L10

Here's how semver handles the precedence of prerelease versions, https://semver.org/#spec-item-9

**Comment by jeromesimeon** [comment]
> [cicero/packages/cicero-core/src/metadata.js](https://github.com/accordproject/cicero/blob/1e82a3f0e21e56b6f58eb3b2e4ba4e00a8aaddce/packages/cicero-core/src/metadata.js#L192)
> Line 192 in [1e82a3f](/accordproject/cicero/commit/1e82a3f0e21e56b6f58eb3b2e4ba4e00a8aaddce)
>  return semver.satisfies(ciceroVersion, this.getTargetVersion());

This might leak in other places, e.g., through:

https://github.com/accordproject/cicero/blob/0d99f921fd076cd700398bf7ef655c7740894a6b/packages/cicero-core/src/metadata.js#L94

I'm investigating.

**Comment by jeromesimeon** [comment]
Having to patch the versions on (one or more) templates locally is time consuming/error prone and doesn't always work (if you get published templates from URL, when you deploy template studio in a staging area for testing, etc).

I'm not sure I see where the harm is to let development versions of Cicero (since those are not installed by end-users but during development) load existing templates with that same version.

With that said, there are a couple of options:
1. move the `.replace(/-\d+$/, '')` inside:
https://github.com/accordproject/cicero/blob/1e82a3f0e21e56b6f58eb3b2e4ba4e00a8aaddce/packages/cicero-core/src/metadata.js#L191
2. bump semver to 5.6.0 and use the option `semver.satisfies(version, range, { includePrerelease: true })`

This second method seems to have a much broader semantic however, since it also allows pre-release in the range from the template itself.

**Comment by mttrbrts** [comment]
I prefer option 2. Let's write some test cases to be explicit about what we want the behaviour to be.

**Comment by jeromesimeon** [comment]
Sounds good. Testing is a little crafty since we effectively access the ciceroVersion directly from the root package.json. I've tested by:
- Adding ciceroVersion as a field in Metadata
- Overriding that field for testing with/without preRelease tag
- Manually changed the root package.json to add a preRelease tag and running tests locally. I'm not sure we want to really do that in automated testing, but this is effectively what the npm publish scripts do.

**Comment by jeromesimeon** [comment]
This should be ready for review. A few additional notes:
- I ended up going back on adding Cicero version to the Metadata since it changes the hash
- Instead I added a version parameter to the satisfies call -- note that this is an API change, so this might force review of the change in other components (although I do believe this is an internal call)
- I changed the `pkgstamp` script to add a minor number for unstable versions

**Pull request merged**
